# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14


# используем режим обычного пользователя для сборки проекта.
sudo: false

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - azzzat72@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always
